version: "3.2"
services:
    # container name
    postgres:
        # build the image from Dockerfile
        build:
            context: ${PWD}/postgresql/
        # bind mount volume for Postgres data
        volumes:
        - $PWD/postgresql/pg-data/:/var/lib/postgresql/pg-data
        - $PWD/code/:/var/www/html
        # open port so host machine can access
        ports:
        - "5432:5432"
        # configure Postgres environment variables
        environment:
        - POSTGRES_USER=docker
        - POSTGRES_DB=covid19
        - POSTGRES_PASSWORD=docker
        networks:
            node_net:
                ipv4_address: 172.28.1.4
    selenium:
        build:
            context: ${PWD}/selenium/
        volumes:
        - ${PWD}/selenium/code:/usr/src/app/code
        networks:
            node_net:
                ipv4_address: 172.28.1.5
networks:
    node_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16